-- ==========================================
-- 1. BACKUP TABEL UT_NOTES
-- ==========================================

CREATE TABLE IF NOT EXISTS public.ut_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users ON DELETE CASCADE DEFAULT auth.uid(),
    created_at timestamp with time zone DEFAULT now(),
    title text NOT NULL,
    content text,
    category text
);

-- Aktifkan RLS (Biar catatan lu gak bisa diintip user lain)
ALTER TABLE public.ut_notes ENABLE ROW LEVEL SECURITY;

-- Policy: Hanya pembuat catatan yang bisa liat/edit/hapus
CREATE POLICY "Users can manage their own notes" 
ON public.ut_notes FOR ALL 
USING (auth.uid() = user_id);


-- ==========================================
-- 2. BACKUP STORAGE (UNTUK AVATAR)
-- ==========================================

-- Bikin Bucket 'avatars'
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Policy: Biar foto avatar bisa dilihat semua orang (Public)
CREATE POLICY "Avatars are public"
ON storage.objects FOR SELECT
USING (bucket_id = 'avatars');

-- Policy: Hanya user yang login yang bisa upload foto ke bucket 'avatars'
CREATE POLICY "Authenticated users can upload avatars"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'avatars' AND auth.role() = 'authenticated');

-- Policy: User hanya bisa update/delete fotonya sendiri
CREATE POLICY "Users can update their own avatars"
ON storage.objects FOR UPDATE
USING (auth.uid() = owner);

CREATE POLICY "Users can delete their own avatars"
ON storage.objects FOR DELETE
USING (auth.uid() = owner);
